# Generated by Django 6.0 on 2025-12-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_experience_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswaprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
